services:
  - type: web
    name: ml-trading-system
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python trading_api.py
    envVars:
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_API_SECRET
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
